Imports

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Imoporting statsmodel

%pip install statsmodels

import statsmodels.api as sm

Requirement already satisfied: statsmodels in c:\users\maxnd\.conda\envs\yolov5\lib\site-packages (0.14.5)
Requirement already satisfied: numpy<3,>=1.22.3 in c:\users\maxnd\appdata\roaming\python\python313\site-packages (from statsmodels) (2.2.3)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in c:\users\maxnd\.conda\envs\yolov5\lib\site-packages (from statsmodels) (1.15.1)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in c:\users\maxnd\.conda\envs\yolov5\lib\site-packages (from statsmodels) (2.2.3)
Requirement already satisfied: patsy>=0.5.6 in c:\users\maxnd\.conda\envs\yolov5\lib\site-packages (from statsmodels) (1.0.1)
Requirement already satisfied: packaging>=21.3 in c:\users\maxnd\.conda\envs\yolov5\lib\site-packages (from statsmodels) (24.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\maxnd\.conda\envs\yolov5\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\maxnd\.conda\envs\yolov5\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\maxnd\.conda\envs\yolov5\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.1)
Requirement already satisfied: six>=1.5 in c:\users\maxnd\.conda\envs\yolov5\lib\site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Dataset

In [3]:
data = {'Name': ["Simson", "Anna", "Peter", "Linda", "Maria", "Daniel", "Simon", "Monica"],
        'Profession':["Data Analyst", "Steward", "Refree", "Mechanic", "Pilot", "Nurse", "Police officer", "Doctor"],
        'Age':[28, 25, 38, 32, 55, 45, 59, 34],
        'Country':["Namibia", "South Africa", "USA", "Canada", "Nigeria", "Germany", "Germany", "Portugal"]}

df = pd.DataFrame(data)

Saving dataset into csv file

In [4]:
df.to_csv("Regression_dset.csv", index=False)

Using the country coloumn

In [8]:
# creating a new coloumn
df["Country_encoder"] = df["Country"].astype("category").cat.codes

In [9]:
pd.read_csv('Regression_dset.csv')

     Name      Profession  Age       Country
0  Simson    Data Analyst   28       Namibia
1    Anna         Steward   25  South Africa
2   Peter          Refree   38           USA
3   Linda        Mechanic   32        Canada
4   Maria           Pilot   55       Nigeria
5  Daniel           Nurse   45       Germany
6   Simon  Police officer   59       Germany
7  Monica          Doctor   34      Portugal

In [12]:
X = df["Country_encoder"]
y = df["Age"]
pd.read_csv('Regression_dset.csv')

     Name      Profession  Age       Country
0  Simson    Data Analyst   28       Namibia
1    Anna         Steward   25  South Africa
2   Peter          Refree   38           USA
3   Linda        Mechanic   32        Canada
4   Maria           Pilot   55       Nigeria
5  Daniel           Nurse   45       Germany
6   Simon  Police officer   59       Germany
7  Monica          Doctor   34      Portugal

way of adding a new constant

In [14]:
X = df["Country_encoder"]
y = df["Age"]

X = sm.add_constant(X)

#developing model
model = sm.OLS(y, X).fit()

model.summary()

c:\Users\maxnd\.conda\envs\yolov5\Lib\site-packages\scipy\stats\_axis_nan_policy.py:430: UserWarning: `kurtosistest` p-value may be inaccurate with fewer than 20 observations; only n=8 observations were given.
  return hypotest_fun_in(*args, **kwds)

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    Age   R-squared:                       0.089
Model:                            OLS   Adj. R-squared:                 -0.063
Method:                 Least Squares   F-statistic:                    0.5844
Date:                Sat, 12 Jul 2025   Prob (F-statistic):              0.474
Time:                        22:12:58   Log-Likelihood:                -30.608
No. Observations:                   8   AIC:                             65.22
Df Residuals:                       6   BIC:                             65.38
Df Model:                           1
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
const              44.3016      7.746      5.720      0.001      25.349      63.254
Country_encoder    -1.7460      2.284     -0.764      0.474      -7.335       3.843
==============================================================================
Omnibus:                        1.407   Durbin-Watson:                   2.089
Prob(Omnibus):                  0.495   Jarque-Bera (JB):                0.737
Skew:                           0.311   Prob(JB):                        0.692
Kurtosis:                       1.649   Cond. No.                         6.14
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

Multiple regression analysis

In [17]:
# working with multiple values

df["Name_encode"] = df["Name"].astype("category").cat.codes
pd.read_csv('Regression_dset.csv')

     Name      Profession  Age       Country
0  Simson    Data Analyst   28       Namibia
1    Anna         Steward   25  South Africa
2   Peter          Refree   38           USA
3   Linda        Mechanic   32        Canada
4   Maria           Pilot   55       Nigeria
5  Daniel           Nurse   45       Germany
6   Simon  Police officer   59       Germany
7  Monica          Doctor   34      Portugal

In [20]:
X = df[["Country_encoder", "Name_encode"]]

X = sm.add_constant(X)

#developing model
model = sm.OLS(y, X).fit()

model.summary()

c:\Users\maxnd\.conda\envs\yolov5\Lib\site-packages\scipy\stats\_axis_nan_policy.py:430: UserWarning: `kurtosistest` p-value may be inaccurate with fewer than 20 observations; only n=8 observations were given.
  return hypotest_fun_in(*args, **kwds)

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    Age   R-squared:                       0.128
Model:                            OLS   Adj. R-squared:                 -0.221
Method:                 Least Squares   F-statistic:                    0.3672
Date:                Sat, 12 Jul 2025   Prob (F-statistic):              0.710
Time:                        22:19:09   Log-Likelihood:                -30.432
No. Observations:                   8   AIC:                             66.86
Df Residuals:                       5   BIC:                             67.10
Df Model:                           2
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
const              40.6899     11.258      3.614      0.015      11.750      69.629
Country_encoder    -1.7141      2.448     -0.700      0.515      -8.008       4.580
Name_encode         1.0068      2.120      0.475      0.655      -4.444       6.457
==============================================================================
Omnibus:                        0.654   Durbin-Watson:                   1.717
Prob(Omnibus):                  0.721   Jarque-Bera (JB):                0.515
Skew:                           0.130   Prob(JB):                        0.773
Kurtosis:                       1.784   Cond. No.                         11.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""